
  - name: "update and upgrade packages"
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: remove unneeded deps  #auto apt remove
    become: yes
    apt:
       autoremove: yes
  - name: install deps  #install nodejs and npm
    become: yes
    apt:     
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes
  - name: "install pm2"  #sudo npm install pm2
    become: yes
    npm:
       name: pm2
       global: yes
       production: yes
       state: present